In [6]:
import pandas as pd
source =pd.read_csv("Employee.csv",sep=",")
print("Test Case 1: Following are the column names in the source file : \n") 
print(source.columns) 
print("\n")
print("Test Case 2: Rows X colums in the source file \n")
print(source.shape)
print("\n")
print("Test Case 3: No. of rows under each columns \n")
print(source.count())
print("\n")
print("Test Case 4: Duplicate records in the source \n")
print(source.duplicated().sum())
print("\n")
print("Test Case 5: Duplicate records saved in the file below \n") 
dupes = source[source.duplicated()].to_csv("duplicated.csv") 
print("\n")
print("Test Case 6: Check if NULL value exist in dept_name column \n") 
print(source[source['dept_name'].isnull()]) 
print("\n") 
print("Test Case 7: Unique value of emp_no column in the source \n") 
print(source['emp_no'].unique()) 
print("\n")

print("Test Case 8: Unique value of emp_name column in the source \n") 
print (source [ 'emp_name' ].unique()) 
print("\n")

print("Test Case 9: Unique value of dept_name column in the source \n") 
print (source [ 'dept_name' ].unique()) 
print("\n")

print("Test Case 10: Unique value of Salary column in the source \n")

print(source['Salary'].unique())

print("\n")

print ("Test Case 11: Sample ( top 5 ) records from source file \n")

print(source.head())

print("TEST COMPLETED____\n")

print("Test Case 12: Sample ( bottom 5 ) records from source file \n")

print(source.tail())

print("TEST COMPLETED____\n")

Test Case 1: Following are the column names in the source file :

Index(['emp_no', 'emp_name', 'dept_name', 'Salary'], dtype='object')


Test Case 2: Rows X colums in the source file

(9, 4)


Test Case 3: No. of rows under each columns

emp_no       9
emp_name     9
dept_name    8
Salary       8
dtype: int64


Test Case 4: Duplicate records in the source

1


Test Case 5: Duplicate records saved in the file below



Test Case 6: Check if NULL value exist in dept_name column

   emp_no emp_name dept_name  Salary
2       2    Peter       NaN  4000.0


Test Case 7: Unique value of emp_no column in the source

[1 2 3 4 5 6 7]


Test Case 8: Unique value of emp_name column in the source

['Adam' 'Peter' 'Christopher' 'Alan' 'Mayank' 'Rakesh' 'Mathew']


Test Case 9: Unique value of dept_name column in the source

['IT' nan 'Finance' 'Sales' 'HR']


Test Case 10: Unique value of Salary column in the source

[1000. 4000.   nan]


Test Case 11: Sample ( top 5 ) records from source file

   emp_no     emp_name dept_name  Salary
0       1         Adam        IT  1000.0
1       1         Adam        IT  1000.0
2       2        Peter       NaN  4000.0
3       3  Christopher   Finance  1000.0
4       4  Christopher   Finance  1000.0
TEST COMPLETED____

Test Case 12: Sample ( bottom 5 ) records from source file

   emp_no     emp_name dept_name  Salary
4       4  Christopher   Finance  1000.0
5       4         Alan     Sales     NaN
6       5       Mayank        HR  4000.0
7       6       Rakesh     Sales  4000.0
8       7       Mathew   Finance  4000.0
TEST COMPLETED____